#!/usr/bin/env node
/**
 * Build-time stat extraction. Parses ../AI_TIME_LOG.md (the Atlas's
 * canonical time log) and emits src/data/timeLogStats.ts so the
 * Marginalia bundle can render aggregate stats without a runtime fetch.
 *
 * Runs as a `predev` and `prebuild` hook so dev and prod stay in sync
 * with whatever's currently committed at the repo root. Cloudflare Pages
 * has access to the parent directory because it clones the full repo
 * before changing into the `marginalia/` root.
 *
 * Window definitions:
 *   - week: rows whose date falls within 7 days of the most recent row's
 *     date (anchor on the data, not on the build clock — consistent
 *     across builds).
 *   - allTime: every parseable row.
 */

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname } from 'node:path';

const SOURCE = '../AI_TIME_LOG.md';
const OUT = 'src/data/timeLogStats.ts';

const text = readFileSync(SOURCE, 'utf8');
const lines = text.split('\n');

const headerIdx = lines.findIndex((l) => /^\|\s*Date\s*\|.*PR.*Scope/i.test(l));
if (headerIdx === -1) {
  console.error(`Could not find data table header in ${SOURCE}`);
  process.exit(1);
}

const parseHours = (cell) => {
  const m = cell
    .replace(/[*_~`]/g, '')
    .trim()
    .match(/^(-?[\d.]+)h$/);
  return m ? parseFloat(m[1]) : null;
};

const parseDate = (cell) => {
  const trimmed = cell.trim();
  if (/^\d{4}-\d{2}-\d{2}$/.test(trimmed)) return trimmed;
  return null;
};

const rows = [];
for (let i = headerIdx + 2; i < lines.length; i += 1) {
  const line = lines[i];
  if (!line.startsWith('|')) break;
  if (/^\|\s*-+/.test(line)) continue;
  const cells = line
    .split('|')
    .slice(1, -1)
    .map((c) => c.trim());
  if (cells.length < 9) continue;
  const solo = parseHours(cells[5]);
  const ai = parseHours(cells[6]);
  const saved = parseHours(cells[7]);
  if (solo === null || ai === null || saved === null) continue;
  const date = parseDate(cells[0]);
  rows.push({ date, solo, ai, saved });
}

if (rows.length === 0) {
  console.error('No parseable rows found in AI_TIME_LOG.md');
  process.exit(1);
}

const sum = (arr) =>
  arr.reduce(
    (acc, r) => ({
      solo: acc.solo + r.solo,
      ai: acc.ai + r.ai,
      saved: acc.saved + r.saved,
      count: acc.count + 1,
    }),
    { solo: 0, ai: 0, saved: 0, count: 0 },
  );

const allTime = sum(rows);

// Anchor "this week" on the most recent dated row, not on `new Date()`,
// so the figure is stable across builds. The most recent row is the
// closest thing to "now" the data itself knows about.
const datedRows = rows.filter((r) => r.date);
const datesSorted = [...new Set(datedRows.map((r) => r.date))].sort();
const mostRecent = datesSorted[datesSorted.length - 1];
const cutoff = new Date(mostRecent);
cutoff.setUTCDate(cutoff.getUTCDate() - 6);
const cutoffStr = cutoff.toISOString().slice(0, 10);
const weekRows = datedRows.filter((r) => r.date >= cutoffStr);
const week = sum(weekRows);

const round = (n) => Math.round(n * 10) / 10;

const stats = {
  generatedAt: new Date().toISOString(),
  windowAnchor: mostRecent,
  weekStart: cutoffStr,
  week: {
    solo: round(week.solo),
    ai: round(week.ai),
    saved: round(week.saved),
    rowCount: week.count,
  },
  allTime: {
    solo: round(allTime.solo),
    ai: round(allTime.ai),
    saved: round(allTime.saved),
    rowCount: allTime.count,
  },
  // Per-row data is exported so post pages can window arbitrary ranges
  // (each post defines its own coversFrom/coversTo). Undated rows
  // (e.g., possible future meta rows) are dropped — they can't be
  // attributed to a window anyway.
  rows: datedRows.map((r) => ({
    date: r.date,
    solo: r.solo,
    ai: r.ai,
    saved: r.saved,
  })),
};

const file = `// GENERATED FILE — do not edit by hand.
// Regenerated by marginalia/scripts/build-stats.mjs from ../AI_TIME_LOG.md
// at every \`yarn dev\` and \`yarn build\` (predev/prebuild hooks).

export type TimeLogWindow = {
  solo: number;
  ai: number;
  saved: number;
  rowCount: number;
};

export type TimeLogRow = {
  date: string;
  solo: number;
  ai: number;
  saved: number;
};

export type TimeLogStats = {
  generatedAt: string;
  windowAnchor: string;
  weekStart: string;
  week: TimeLogWindow;
  allTime: TimeLogWindow;
  rows: TimeLogRow[];
};

export const timeLogStats: TimeLogStats = ${JSON.stringify(stats, null, 2)};
`;

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, file);

console.log(
  `marginalia/build-stats: ${rows.length} rows parsed; week (${cutoffStr} → ${mostRecent}) ${week.count} rows, all-time ${allTime.count} rows.`,
);
