// GENERATED FILE — do not edit by hand.
// Regenerated by marginalia/scripts/build-stats.mjs from ../AI_TIME_LOG.md
// at every `yarn dev` and `yarn build` (predev/prebuild hooks).

export type TimeLogWindow = {
  solo: number;
  ai: number;
  saved: number;
  rowCount: number;
};

export type TimeLogStats = {
  generatedAt: string;
  windowAnchor: string;
  weekStart: string;
  week: TimeLogWindow;
  allTime: TimeLogWindow;
};

export const timeLogStats: TimeLogStats = {
  "generatedAt": "2026-05-09T19:47:50.429Z",
  "windowAnchor": "2026-05-09",
  "weekStart": "2026-05-03",
  "week": {
    "solo": 189.1,
    "ai": 34.8,
    "saved": 154.3,
    "rowCount": 78
  },
  "allTime": {
    "solo": 312.1,
    "ai": 71.3,
    "saved": 240.8,
    "rowCount": 80
  }
};
