// GENERATED FILE — do not edit by hand.
// Regenerated by marginalia/scripts/build-stats.mjs from ../AI_TIME_LOG.md
// at every `yarn dev` and `yarn build` (predev/prebuild hooks).

export type TimeLogWindow = {
  solo: number;
  ai: number;
  saved: number;
  rowCount: number;
};

export type TimeLogRow = {
  date: string;
  solo: number;
  ai: number;
  saved: number;
};

export type TimeLogStats = {
  generatedAt: string;
  windowAnchor: string;
  weekStart: string;
  week: TimeLogWindow;
  allTime: TimeLogWindow;
  rows: TimeLogRow[];
};

export const timeLogStats: TimeLogStats = {
  "generatedAt": "2026-05-09T19:51:53.587Z",
  "windowAnchor": "2026-05-09",
  "weekStart": "2026-05-03",
  "week": {
    "solo": 189.1,
    "ai": 34.8,
    "saved": 154.3,
    "rowCount": 78
  },
  "allTime": {
    "solo": 312.1,
    "ai": 71.3,
    "saved": 240.8,
    "rowCount": 80
  },
  "rows": [
    {
      "date": "2026-05-09",
      "solo": 6,
      "ai": 1.5,
      "saved": 4.5
    },
    {
      "date": "2026-05-08",
      "solo": 0.25,
      "ai": 0.1,
      "saved": 0.15
    },
    {
      "date": "2026-05-08",
      "solo": 0.75,
      "ai": 0.2,
      "saved": 0.55
    },
    {
      "date": "2026-05-08",
      "solo": 0.5,
      "ai": 0.15,
      "saved": 0.35
    },
    {
      "date": "2026-05-08",
      "solo": 0.5,
      "ai": 0.15,
      "saved": 0.35
    },
    {
      "date": "2026-05-08",
      "solo": 0.5,
      "ai": 0.15,
      "saved": 0.35
    },
    {
      "date": "2026-05-08",
      "solo": 0.25,
      "ai": 0.1,
      "saved": 0.15
    },
    {
      "date": "2026-05-08",
      "solo": 0.5,
      "ai": 0.15,
      "saved": 0.35
    },
    {
      "date": "2026-05-08",
      "solo": 0.25,
      "ai": 0.1,
      "saved": 0.15
    },
    {
      "date": "2026-05-08",
      "solo": 0.25,
      "ai": 0.1,
      "saved": 0.15
    },
    {
      "date": "2026-05-08",
      "solo": 1,
      "ai": 0.3,
      "saved": 0.7
    },
    {
      "date": "2026-05-08",
      "solo": 0.5,
      "ai": 0.15,
      "saved": 0.35
    },
    {
      "date": "2026-05-08",
      "solo": 0.25,
      "ai": 0.1,
      "saved": 0.15
    },
    {
      "date": "2026-05-08",
      "solo": 0.5,
      "ai": 0.15,
      "saved": 0.35
    },
    {
      "date": "2026-05-08",
      "solo": 0.75,
      "ai": 0.25,
      "saved": 0.5
    },
    {
      "date": "2026-05-08",
      "solo": 0.1,
      "ai": 0.05,
      "saved": 0.05
    },
    {
      "date": "2026-05-08",
      "solo": 0.5,
      "ai": 0.15,
      "saved": 0.35
    },
    {
      "date": "2026-05-08",
      "solo": 1.5,
      "ai": 0.4,
      "saved": 1.1
    },
    {
      "date": "2026-05-08",
      "solo": 0.5,
      "ai": 0.15,
      "saved": 0.35
    },
    {
      "date": "2026-05-08",
      "solo": 0.5,
      "ai": 0.15,
      "saved": 0.35
    },
    {
      "date": "2026-05-08",
      "solo": 3,
      "ai": 0.6,
      "saved": 2.4
    },
    {
      "date": "2026-05-08",
      "solo": 1.5,
      "ai": 0.4,
      "saved": 1.1
    },
    {
      "date": "2026-05-08",
      "solo": 0.5,
      "ai": 0.15,
      "saved": 0.35
    },
    {
      "date": "2026-05-08",
      "solo": 2,
      "ai": 0.5,
      "saved": 1.5
    },
    {
      "date": "2026-05-08",
      "solo": 1,
      "ai": 0.3,
      "saved": 0.7
    },
    {
      "date": "2026-05-08",
      "solo": 0.75,
      "ai": 0.2,
      "saved": 0.55
    },
    {
      "date": "2026-05-08",
      "solo": 3,
      "ai": 0.6,
      "saved": 2.4
    },
    {
      "date": "2026-05-08",
      "solo": 0.25,
      "ai": 0.1,
      "saved": 0.15
    },
    {
      "date": "2026-05-08",
      "solo": 10,
      "ai": 1.75,
      "saved": 8.25
    },
    {
      "date": "2026-05-08",
      "solo": 2,
      "ai": 0.5,
      "saved": 1.5
    },
    {
      "date": "2026-05-08",
      "solo": 1.5,
      "ai": 0.35,
      "saved": 1.15
    },
    {
      "date": "2026-05-08",
      "solo": 1,
      "ai": 0.25,
      "saved": 0.75
    },
    {
      "date": "2026-05-08",
      "solo": 0.25,
      "ai": 0.1,
      "saved": 0.15
    },
    {
      "date": "2026-05-08",
      "solo": 0.5,
      "ai": 0.15,
      "saved": 0.35
    },
    {
      "date": "2026-05-08",
      "solo": 1.75,
      "ai": 0.5,
      "saved": 1.25
    },
    {
      "date": "2026-05-08",
      "solo": 4,
      "ai": 0.4,
      "saved": 3.6
    },
    {
      "date": "2026-05-08",
      "solo": 1,
      "ai": 0.2,
      "saved": 0.8
    },
    {
      "date": "2026-05-08",
      "solo": 10,
      "ai": 0.5,
      "saved": 9.5
    },
    {
      "date": "2026-05-08",
      "solo": 8,
      "ai": 0.4,
      "saved": 7.6
    },
    {
      "date": "2026-05-08",
      "solo": 12,
      "ai": 0.6,
      "saved": 11.4
    },
    {
      "date": "2026-05-08",
      "solo": 0.5,
      "ai": 0.15,
      "saved": 0.35
    },
    {
      "date": "2026-05-08",
      "solo": 2,
      "ai": 0.4,
      "saved": 1.6
    },
    {
      "date": "2026-05-08",
      "solo": 0.2,
      "ai": 0.08,
      "saved": 0.12
    },
    {
      "date": "2026-05-08",
      "solo": 0.25,
      "ai": 0.08,
      "saved": 0.17
    },
    {
      "date": "2026-05-08",
      "solo": 1.5,
      "ai": 0.3,
      "saved": 1.2
    },
    {
      "date": "2026-05-08",
      "solo": 3,
      "ai": 0.5,
      "saved": 2.5
    },
    {
      "date": "2026-05-07",
      "solo": 0.75,
      "ai": 0.1,
      "saved": 0.65
    },
    {
      "date": "2026-05-07",
      "solo": 0.5,
      "ai": 0.1,
      "saved": 0.4
    },
    {
      "date": "2026-05-07",
      "solo": 8,
      "ai": 1.5,
      "saved": 6.5
    },
    {
      "date": "2026-05-07",
      "solo": 5,
      "ai": 0.75,
      "saved": 4.25
    },
    {
      "date": "2026-05-06",
      "solo": 4,
      "ai": 0.5,
      "saved": 3.5
    },
    {
      "date": "2026-05-06",
      "solo": 5,
      "ai": 0.75,
      "saved": 4.25
    },
    {
      "date": "2026-05-06",
      "solo": 2,
      "ai": 0.5,
      "saved": 1.5
    },
    {
      "date": "2026-05-06",
      "solo": 0.75,
      "ai": 0.15,
      "saved": 0.6
    },
    {
      "date": "2026-05-06",
      "solo": 0.3,
      "ai": 0.1,
      "saved": 0.2
    },
    {
      "date": "2026-05-05",
      "solo": 12,
      "ai": 2,
      "saved": 10
    },
    {
      "date": "2026-05-05",
      "solo": 1.5,
      "ai": 0.25,
      "saved": 1.25
    },
    {
      "date": "2026-05-05",
      "solo": 1.5,
      "ai": 0.3,
      "saved": 1.2
    },
    {
      "date": "2026-05-05",
      "solo": 3,
      "ai": 0.75,
      "saved": 2.25
    },
    {
      "date": "2026-05-05",
      "solo": 1,
      "ai": 0.25,
      "saved": 0.75
    },
    {
      "date": "2026-05-05",
      "solo": 1.5,
      "ai": 0.3,
      "saved": 1.2
    },
    {
      "date": "2026-05-05",
      "solo": 0.75,
      "ai": 0.15,
      "saved": 0.6
    },
    {
      "date": "2026-05-04",
      "solo": 4,
      "ai": 0.75,
      "saved": 3.25
    },
    {
      "date": "2026-05-03",
      "solo": 3,
      "ai": 0.5,
      "saved": 2.5
    },
    {
      "date": "2026-05-03",
      "solo": 6,
      "ai": 1,
      "saved": 5
    },
    {
      "date": "2026-05-03",
      "solo": 2,
      "ai": 0.5,
      "saved": 1.5
    },
    {
      "date": "2026-05-03",
      "solo": 2,
      "ai": 0.5,
      "saved": 1.5
    },
    {
      "date": "2026-05-03",
      "solo": 1.5,
      "ai": 0.25,
      "saved": 1.25
    },
    {
      "date": "2026-05-03",
      "solo": 6,
      "ai": 1.5,
      "saved": 4.5
    },
    {
      "date": "2026-05-03",
      "solo": 3,
      "ai": 0.5,
      "saved": 2.5
    },
    {
      "date": "2026-05-03",
      "solo": 10,
      "ai": 2.5,
      "saved": 7.5
    },
    {
      "date": "2026-05-03",
      "solo": 0.5,
      "ai": 0.1,
      "saved": 0.4
    },
    {
      "date": "2026-05-03",
      "solo": 3,
      "ai": 0.75,
      "saved": 2.25
    },
    {
      "date": "2026-05-03",
      "solo": 1.5,
      "ai": 0.25,
      "saved": 1.25
    },
    {
      "date": "2026-05-03",
      "solo": 5,
      "ai": 1.25,
      "saved": 3.75
    },
    {
      "date": "2026-05-03",
      "solo": 3,
      "ai": 0.75,
      "saved": 2.25
    },
    {
      "date": "2026-05-03",
      "solo": 3,
      "ai": 0.5,
      "saved": 2.5
    },
    {
      "date": "2026-05-03",
      "solo": 0.75,
      "ai": 0.15,
      "saved": 0.6
    },
    {
      "date": "2026-05-02",
      "solo": 3,
      "ai": 0.5,
      "saved": 2.5
    },
    {
      "date": "2026-05-01",
      "solo": 120,
      "ai": 36,
      "saved": 84
    }
  ]
};
