#!/usr/bin/env bash
# Regenerate all branding PNGs from their source SVGs in public/.
#
# Sources (committed, edit these):
#   public/favicon.svg        — italic A. mark, master for all icon sizes
#   public/og-image.svg       — Open Graph / Twitter share card (1200×630)
#   public/profile-image.svg  — padded A. mark for social profile pictures
#
# Outputs (also committed, regenerated by this script):
#   public/favicon-16.png       16×16
#   public/favicon-32.png       32×32
#   public/favicon-192.png      192×192
#   public/favicon-512.png      512×512
#   public/apple-touch-icon.png 180×180
#   public/og-image.png         1200×630
#   public/profile-image.png    1024×1024
#
# Prerequisites:
#   - rsvg-convert        (brew install librsvg)
#   - Fraunces installed locally for fontconfig
#                         (brew install --cask font-fraunces)
#   - IBM Plex Sans + Mono for the OG card
#                         (brew install --cask font-ibm-plex-sans font-ibm-plex-mono)

set -euo pipefail

cd "$(dirname "$0")/.."

if ! command -v rsvg-convert >/dev/null 2>&1; then
  echo "error: rsvg-convert not found. Install with: brew install librsvg" >&2
  exit 1
fi

ICON_SRC=public/favicon.svg
OG_SRC=public/og-image.svg
PROFILE_SRC=public/profile-image.svg

render_icon() {
  local size=$1 out=$2
  rsvg-convert -w "$size" -h "$size" "$ICON_SRC" -o "$out"
  echo "  rendered $out (${size}×${size})"
}

echo "Rendering favicons from $ICON_SRC"
render_icon 16  public/favicon-16.png
render_icon 32  public/favicon-32.png
render_icon 192 public/favicon-192.png
render_icon 512 public/favicon-512.png
render_icon 180 public/apple-touch-icon.png

echo "Rendering OG card from $OG_SRC"
rsvg-convert -w 1200 -h 630 "$OG_SRC" -o public/og-image.png
echo "  rendered public/og-image.png (1200×630)"

echo "Rendering social profile image from $PROFILE_SRC"
rsvg-convert -w 1024 -h 1024 "$PROFILE_SRC" -o public/profile-image.png
echo "  rendered public/profile-image.png (1024×1024)"

echo "Done."
